### PR TITLE
Alternative mouse detect method

### PR DESCRIPTION
**Pull request by iansedano**
The weird clicking bugs I was getting were due to the dragging detection sometimes giving a false positive. Here is a method that seems to work well on my end.

### CODE REVIEW

**Comment by iansedano** [comment]
With some more time to think about this... for smooth orbiting, I think you will need a mousemove handler. But I think you could potentially leave the smoothness until after you've got orbiting working.

**Comment by LiveNathan** [comment]
> The weird clicking bugs I was getting were due to the dragging detection sometimes giving a false positive. Here is a method that seems to work well on my end.

oh, interesting. So, this is a PR that you made? So I should be able to load it and read the code? But there's still another PR open. I wonder what that will do.

**Comment by LiveNathan** [comment]
I'm not sure how to load this into my IDE. Normally it would just show up on the list of branches to choose from.

**Comment by LiveNathan** [comment]
ok, I can see how to view the diff either here on in my IDE, but not to just load the project with your changes. So I guess I'll accept the changes and then see if I can open the project.

**Review by LiveNathan — APPROVED** [review]
👍

**Comment by LiveNathan** [comment]
Ok, I got it. Clicking seems to work well. Not sure if it's improved for me. Maybe a bit. Maybe we can talk through it at the next meeting.

**Pull request merged**
